version: '3.7'

services:
  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: DB_ASSESSEMENT
      command: --init-file /data/application/init.sql
    volumes:
      - ./database/mysql-data:/var/lib/mysql:rw
      - ./init.sql:/data/application/init.sql

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: mysql

  app:
    build: .
    container_name: app
    hostname: app
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    ports:
      - "3001:8080"
    depends_on:
      - mysql

volumes:
  mysql-data:

networks:
  default:

